[package]
name = "Linn"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = { version = "0.10", features = ["libadwaita", "macros"] }
gtk4 = "0.10"
adw = { package = "libadwaita", version = "0.8" }